Implementing Spaces
mautrix/imessage pull request #55
Opened 2022-04-08 21:10 UTC by shreyasajj

I think have implemented spaces correctly, I have done some decent testing but let me know if it works for you

2022-04-09 01:35 UTC, sumnerevans requested changes
I haven't had a chance to review in-depth, but at first glance, it looks sane.

2022-04-09 01:35 UTC, sumnerevans commented on example-config.yaml
> +        # The Image of the space
```suggestion
        # The MXC URI of the space
```

2022-04-09 01:35 UTC, sumnerevans commented on user.go
> +
```suggestion
```

2022-04-09 01:35 UTC, sumnerevans commented on portal.go
> +
```suggestion
```

2022-04-12 19:44 UTC, shreyasajj commented
I didn't hear anything back in a while and I wanted to check in. Did something go wrong, I would love to help you fix it

2022-04-20 02:36 UTC, shreyasajj commented
There has been one problem I have noticed so far is that it says it changes it avatar image 4 times in a row for the imessage bridge bot. Not sure if that related to this or another problem but really just a minor inconvenience

2022-05-01 08:34 UTC, closed without merging